### PR TITLE
Bump DFL version to 3.25.0

### LINKED ISSUE #6: New decky loader breaks plugin
When trying to launch plugin in Decky version 2.11.1

I receive the error:
TypeError: Cannot read properties of undefined (reading 'SimpleModal')
at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43),  <anonymous:366:17)
at eval (eval at importReactPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43),  <anonymous:2848:3)
at PluginLoader.importReactPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43)
at async PluginLoader.importPlugin (http://localhost:1337/frontend/chunk/-5ac6285.js:6900:43)

### PR DESCRIPTION
**Pull request by d3m3vilurr**
resolve #6 and support recent steamos's CSS class changes

### CODE REVIEW

**Comment by safijari** [comment]
I'm forking this repo and will be moving it to using global DFL. If the Decky folks allow it I will switch over the store version of the plugin to my fork and minimally mainten until the author resurfaces.

**Comment by deanh** [comment]
> I'm forking this repo and will be moving it to using global DFL. If the Decky folks allow it I will switch over the store version of the plugin to my fork and minimally mainten until the author resurfaces.

Is there a way to install the fork now? I just tried to install the Decky version and ran into issues. I'm brand new to Decky, I found it because I was looking to get a save organizer working on Steam Deck for DS3 and Elden Ring and I saw this plugin. :)

**Comment by metehankutlu** [comment]
Sorry guys I was away for a while but it seems it is resolved.

**Comment by deanh** [comment]
Hi there. I just tried installing again via Decky and got the same error. Has the fix been published, or is there a straightforward way to install from Github? Thanks.

**Comment by safijari** [comment]
> Sorry guys I was away for a while but it seems it is resolved.

If you're active again please change the plugin back to your own repo and I'll delete the SDH-Stewardship fork.

Thanks.

**Comment by sickhate** [comment]
It still doesnt work no games or options show up…

**Comment by ttang4299** [comment]
@metehankutlu Hi, do you know when these changes can come to a stable release of the plugin?

**Comment by ttang4299** [comment]
Still no stable release, looks like @metehankutlu @metehan-kutlu has abandoned us again...

**Comment by ttang4299** [comment]
@safijari Maybe the Decky repo should switch over to @d3m3vilurr 's fork

**Comment by safijari** [comment]
@ttang4299 DFL version was already bumped and I put an updated version on the testing store. It seems the plugin had something else wrong with it too since everything ran but did not actually function. If someone has a working fork of this plugin please open a PR against https://github.com/SDH-Stewardship/decky-save-manager and I'd be happy to get it tested and released.

**Comment by ttang4299** [comment]
@d3m3vilurr Would it be possible to keep troubleshooting? Otherwise, I guess maybe it's time to retire this plugin.

**Pull request merged**
